import os

parameters = [
    "Lima_TB",
    "AdaBoost",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_AdaBoost_classifier_result_recorder_5-folds_2016-09-24_16-45-58.csv",
    "Artificial neural network",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_Artificial neural network_classifier_result_recorder_5-folds_2016-09-22_19-56-23.csv",
    "Bernoulli Naive Bayes",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_Bernoulli Naive Bayes_classifier_result_recorder_5-folds_2016-10-24_21-13-04.csv",
    "Decision Tree",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Decision Tree_classifier_result_recorder_5-folds_2016-09-16_14-17-00.csv",
    "Extreme Learning Machine",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_Extreme Learning Machine_classifier_result_recorder_5-folds_2016-10-25_15-09-29.csv",
    "Gaussian Naive Bayes",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_Gaussian Naive Bayes_classifier_result_recorder_5-folds_2016-10-23_14-55-38.csv",
    "K-nearest neighbours",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_K-nearest neighbours_classifier_result_recorder_5-folds_2016-09-23_22-11-35.csv",
    "Logistic regression",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Logistic regression_classifier_result_recorder_5-folds_2016-09-14_09-18-31.csv",
    "Random forest",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_Random forest_classifier_result_recorder_5-folds_2016-09-22_23-27-36.csv",
    "SVM (RBF)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/SVM (RDF)_classifier_result_recorder_5-folds_2016-09-15_23-43-59.csv",
    "SVM (linear)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/SVM (linear)_classifier_result_recorder_5-folds_2016-09-16_06-41-59.csv",
    "SVM (polynomial)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/Lima_TB/Lima_TB_SVM (polynomial)_classifier_result_recorder_5-folds_2016-10-07_19-08-55.csv",
    "next_dataset",
    "India_CHW_attrition",
    "AdaBoost",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_AdaBoost_classifier_result_recorder_5-folds_2016-10-28_06-27-57.csv",
    "Artificial neural network",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Artificial neural network_classifier_result_recorder_5-folds_2016-10-28_15-13-16.csv",
    "Bernoulli Naive Bayes",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Bernoulli Naive Bayes_classifier_result_recorder_5-folds_2016-10-29_04-08-12.csv",
    "Decision Tree",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Decision Tree_classifier_result_recorder_5-folds_2016-11-09_03-35-25.csv",
    "Extreme Learning Machine",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Extreme Learning Machine_classifier_result_recorder_5-folds_2016-10-27_18-17-46.csv",
    "Gaussian Naive Bayes",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Gaussian Naive Bayes_classifier_result_recorder_5-folds_2016-10-27_11-20-48.csv",
    "K-nearest neighbours",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_K-nearest neighbours_classifier_result_recorder_5-folds_2016-11-08_02-13-33.csv",
    "Logistic regression",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Logistic regression_classifier_result_recorder_5-folds_2016-11-07_01-57-42.csv",
    "Random forest",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_Random forest_classifier_result_recorder_5-folds_2016-11-09_15-15-49.csv",
    "SVM (RBF)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_SVM (RDF)_classifier_result_recorder_5-folds_2016-11-07_23-23-17.csv",
    "SVM (linear)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_SVM (linear)_classifier_result_recorder_5-folds_2016-10-27_12-35-33.csv",
    "SVM (polynomial)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/india_attrition/India_CHW_attrition_SVM (polynomial)_classifier_result_recorder_5-folds_2016-11-10_05-27-30.csv",
    "next_dataset",
    "German_credit",
    "AdaBoost",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_AdaBoost_classifier_result_recorder_5-folds_2016-09-26_20-38-38.csv",
    "Artificial neural network",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Artificial neural network_classifier_result_recorder_5-folds_2016-09-24_20-35-43.csv",
    "Bernoulli Naive Bayes",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Bernoulli Naive Bayes_classifier_result_recorder_5-folds_2016-09-27_23-48-06.csv",
    "Decision Tree",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Decision Tree_classifier_result_recorder_5-folds_2016-09-27_21-48-26.csv",
    "Extreme Learning Machine",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Extreme Learning Machine_classifier_result_recorder_5-folds_2016-10-25_15-51-42.csv",
    "Gaussian Naive Bayes",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Gaussian Naive Bayes_classifier_result_recorder_5-folds_2016-10-23_15-12-17.csv",
    "K-nearest neighbours",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_K-nearest neighbours_classifier_result_recorder_5-folds_2016-09-24_17-01-48.csv",
    "Logistic regression",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Logistic regression_classifier_result_recorder_5-folds_2016-09-25_14-43-48.csv",
    "Random forest",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_Random forest_classifier_result_recorder_5-folds_2016-09-26_14-56-54.csv",
    "SVM (RBF)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_SVM (RDF)_classifier_result_recorder_5-folds_2016-09-23_23-54-59.csv",
    "SVM (linear)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_SVM (linear)_classifier_result_recorder_5-folds_2016-09-24_00-23-52.csv",
    "SVM (polynomial)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/German/German_credit_SVM (polynomial)_classifier_result_recorder_5-folds_2016-10-08_01-15-47.csv",
    "next_dataset",
    "Australian_credit",
    "AdaBoost",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_AdaBoost_classifier_result_recorder_5-folds_2016-09-27_09-03-08.csv",
    "Artificial neural network",
    os.path.dirname(
        os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Artificial neural network_classifier_result_recorder_5-folds_2016-09-25_16-17-38.csv",
    "Bernoulli Naive Bayes",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Bernoulli Naive Bayes_classifier_result_recorder_5-folds_2016-09-27_13-57-31.csv",
    "Decision Tree",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Decision Tree_classifier_result_recorder_5-folds_2016-09-27_08-28-46.csv",
    "Extreme Learning Machine",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Extreme Learning Machine_classifier_result_recorder_5-folds_2016-10-25_16-25-36.csv",
    "Gaussian Naive Bayes",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Gaussian Naive Bayes_classifier_result_recorder_5-folds_2016-10-23_15-28-56.csv",
    "K-nearest neighbours",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_K-nearest neighbours_classifier_result_recorder_5-folds_2016-09-27_12-54-39.csv",
    "Logistic regression",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Logistic regression_classifier_result_recorder_5-folds_2016-09-26_14-49-09.csv",
    "Random forest",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_Random forest_classifier_result_recorder_5-folds_2016-09-26_19-40-50.csv",
    "SVM (RBF)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_SVM (RDF)_classifier_result_recorder_5-folds_2016-09-25_19-46-14.csv",
    "SVM (linear)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_SVM (linear)_classifier_result_recorder_5-folds_2016-09-25_19-57-04.csv",
    "SVM (polynomial)",
    os.path.dirname(os.path.realpath(__file__)) + "/../../results/" + "parameter_tests/australia/Australian_credit_SVM (polynomial)_classifier_result_recorder_5-folds_2016-09-27_02-47-16.csv"]
